language: java

# Following https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/7 the trusty the installation of oracle JDK 8 will not fail on trusty while it fails on newer distributions
dist: trusty

#Following https://docs.travis-ci.com/user/languages/java/ we have to run an update for JDK 8
sudo: false

# The following lines have been removed since they caused build errors in Travis
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
      
jdk:  
  - oraclejdk8

before_install:
  - cp src/main/properties/log4j.properties src/test/resources/log4j.properties
  - mkdir -p "gerbil_data"
  - curl --retry 4 -L -o "gerbil_data/gerbil_data.zip" "https://github.com/AKSW/gerbil/releases/download/v1.2.6/gerbil_data.zip"
  - unzip "gerbil_data/gerbil_data.zip"
  - touch src/main/properties/gerbil_keys.properties
  - mkdir -p "gerbil_data/cache"
install:
  - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package -Dmaven.javadoc.skip=true -B
